name: test
channels:
  - defaults
  - psi4/label/dev
dependencies:
    # Base
  - numpy
  - python
  - qcelemental
  - msgpack-python

    # Testing
  - pytest
  - pytest-cov
  - psi4
  - dftd3
  - codecov
