# After changing this file, check it on:
#   http://lint.travis-ci.org/

language: python

# Run jobs on container-based infrastructure, can be overridden per job
sudo: false

python:
    - 2.7
    - 3.5
    - 3.6

before_install:
  - uname -a
  - free -m
  - df -h
  - ulimit -a

install:
    # Pull down a miniconda
  - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"

    # Build out the environment
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  - conda info -a
  - conda create -q -n tenv python=$TRAVIS_PYTHON_VERSION ci-psi4 psi4 numpy -c psi4/label/dev
  - source activate tenv
  - conda install pytest pytest-cov codecov -c conda-forge
  - conda list

before_script:
  - python -V
  - python -c 'import numpy; print(numpy.version.version)'
  - pip install -e .

script:
  - pwd
  - export PYTHONPATH=../:optking/:psi4/:./:tests/
#  - py.test -v --cov=gau2grid/ --durations=5
  - py.test -v -rws --durations=5 --cov

notifications:
  email: false

after_success:
  - codecov

